### ISSUE TITLE
From where to get the coins needed for stacking

### ISSUE THREAD

**Issue by Muhammad-Altabba** [tonlabs/main.ton.dev#12]
From where to get the coins needed for stacking?

**Comment by mdorofeev** [comment]
Same question

**Comment by ar-tmp** [comment]
There are several ways to get tokens - one of them is participation in contests.
You can find information about the contests on https://freeton.org/
Yo can also ask for test tokens (rubies) for net.ton.dev network to make experiments - just fill in https://forms.gle/zCH7dDiR2yC84m5m9 form
