### ISSUE TITLE
INFO: TIME_DIFF​​ not dicrease 

### ISSUE THREAD

**Issue by saingsab** [tonlabs/main.ton.dev#17]
According to the document said 

> If the TIME_DIFF parameter equals a few seconds, synchronization is complete.

But I have ran the node about 24 hours the still high like below:
INFO: TIME_DIFF = -129423

Is there anything to verify please advise.

**Comment by ar-tmp** [comment]
Is it still actual?
If yes please check that you use SSD and enough network throughput (1Gb/sec+)

**Comment by mrayoung** [comment]
I think I have found the issue.
This is why it's couldn't sync due to I use EBS AWS storage. 

<img width="393" alt="image" src="https://user-images.githubusercontent.com/6874962/82985179-c2bec780-a01d-11ea-959e-cb7d16adfdfc.png">

**Comment by saingsab** [comment]
The SSD storage and Connection really matters.
After few try I could get the right spec.
![image](https://user-images.githubusercontent.com/6874962/83519984-1e4df100-a507-11ea-8352-8e5ef4e9b575.png)
