### ISSUE TITLE
Takes up too much space after build

### ISSUE THREAD

**Issue by varnav** [tonlabs/main.ton.dev#2]
Hello!

I'm trying to dockerize the node: https://github.com/varnav/freeton-node-docker

Problem is that after build node takes 18 GB in space. Just build directory is about 8 gigabytes. Is this normal, or is it possible to clean this up after build somehow?

**Comment by ar-tmp** [comment]
Could you please try new build.sh - built binaries should take less disk space now.

**Comment by varnav** [comment]
It's much better now, 1.5 GB - but it's still too much

**Comment by ASLanin** [comment]
Containerization of current release of the node is not planned.
We are planning to implement containerization for  the new version of the node.
