### ISSUE TITLE
deploy_wallet.sh / check_node_sync_status.sh: add check for lite-server availability

### ISSUE THREAD

**Issue by ar-tmp** [tonlabs/main.ton.dev#20]

**Comment by saingsab** [comment]
After running check_node_sync_status.sh and the TIME_DIFF parameter equals a few seconds, synchronization is complete. How to be sure or is there a ways to verify that the node is available and participated on the network.

**Comment by ar-tmp** [comment]
@mrayoung could you please open a new issue for that request? It's a bit off topic for this issue.

**Comment by saingsab** [comment]
I don't think it much critical since the "SSD disks are recommended for /var/ton-work/db storage." already mentioned on the setup guide. 

But would be great you can state the IO spec, my issue already solved after change the SSD type.
