### ISSUE TITLE
curl in build.sh

### ISSUE THREAD

**Issue by Custler** [tonlabs/main.ton.dev#24]
You forget to add curl to the list of packages

**Comment by varnav** [comment]
Also `pkg-config` and `libreadline8`

**Comment by ar-tmp** [comment]
`curl` has been added.
@varnav did you observe any related script failures?

**Comment by varnav** [comment]
For me check_node_sync_status.sh failed without libreadline8, and SSL build failed in cargo without pkg-config.

Ubuntu 20.04 Docker image. Not sure if it will happen with regular Ubuntu. I fixed it in my docker build: https://github.com/varnav/freeton-node-docker

**Comment by Custler** [comment]
@varnav 
I installed Ubuntu 20.04 on bare hardware. It does not need any additional packages. Only `git` for first download. One difference is that installation was in datacenter. They may use modified distro.

**Comment by ASLanin** [comment]
Ubuntu 20.04 is not fully tested.
Original issue was fixed.
