### ISSUE TITLE
Cannot build a node: Linking CXX sta...arty/rocksdb/librocksdb.a ninja: build stopped: subcommand failed.

### ISSUE THREAD

**Issue by stakrspace** [tonlabs/main.ton.dev#3]
[504/941] Generate common tl source files
FAILED: ../tl/generate/auto/tl/ton_api.cpp ../tl/generate/auto/tl/ton_api.h ../tl/generate/auto/tl/ton_api.hpp ../tl/generate/auto/tl/ton_api_json.cpp ../tl/generate/auto/tl/ton_api_json.h ../tl/generate/auto/tl/lite_api.cpp ../tl/generate/auto/tl/lite_api.h ../tl/generate/auto/tl/lite_api.hpp ../tl/generate/auto/tl/tonlib_api.cpp ../tl/generate/auto/tl/tonlib_api.h ../tl/generate/auto/tl/tonlib_api.hpp ../tl/generate/auto/tl/tonlib_api_json.cpp ../tl/generate/auto/tl/tonlib_api_json.h 
cd /root/main.ton.dev/ton/tl/generate && /root/main.ton.dev/ton/build/tl/generate/generate_common
Illegal instruction
[521/941] Building CXX object tdac...iles/benchmark.dir/benchmark.cpp.o
ninja: build stopped: subcommand failed.

[518/941] Generate common tl source files
FAILED: ../tl/generate/auto/tl/ton_api.cpp ../tl/generate/auto/tl/ton_api.h ../tl/generate/auto/tl/ton_api.hpp ../tl/generate/auto/tl/ton_api_json.cpp ../tl/generate/auto/tl/ton_api_json.h ../tl/generate/auto/tl/lite_api.cpp ../tl/generate/auto/tl/lite_api.h ../tl/generate/auto/tl/lite_api.hpp ../tl/generate/auto/tl/tonlib_api.cpp ../tl/generate/auto/tl/tonlib_api.h ../tl/generate/auto/tl/tonlib_api.hpp ../tl/generate/auto/tl/tonlib_api_json.cpp ../tl/generate/auto/tl/tonlib_api_json.h 
cd /root/main.ton.dev/ton/tl/generate && /root/main.ton.dev/ton/build/tl/generate/generate_common
Illegal instruction
[535/941] Building CXX object cryp...s/ton_crypto.dir/vm/stackops.cpp.o
ninja: build stopped: subcommand failed.

       ^
[575/941] Generate common tl source files
FAILED: ../tl/generate/auto/tl/ton_api.cpp ../tl/generate/auto/tl/ton_api.h ../tl/generate/auto/tl/ton_api.hpp ../tl/generate/auto/tl/ton_api_json.cpp ../tl/generate/auto/tl/ton_api_json.h ../tl/generate/auto/tl/lite_api.cpp ../tl/generate/auto/tl/lite_api.h ../tl/generate/auto/tl/lite_api.hpp ../tl/generate/auto/tl/tonlib_api.cpp ../tl/generate/auto/tl/tonlib_api.h ../tl/generate/auto/tl/tonlib_api.hpp ../tl/generate/auto/tl/tonlib_api_json.cpp ../tl/generate/auto/tl/tonlib_api_json.h 
cd /root/main.ton.dev/ton/tl/generate && /root/main.ton.dev/ton/build/tl/generate/generate_common
Illegal instruction
[583/941] Linking CXX static library third-party/rocksdb/librocksdb.a
ninja: build stopped: subcommand failed.

In file included from ../crypto/tl/tlbc.cpp:3061:0:
../crypto/tl/tlbc-gen-cpp.cpp: In member function 'bool tlbc::CppTypeCode::output_print_simple_field(std::ostream&, const tlbc::Field&, std::__cxx11::string, const tlbc::TypeExpr*)':
../crypto/tl/tlbc-gen-cpp.cpp:2171:7: warning: unused variable 'l' [-Wunused-variable]
   int l = (sz.is_fixed() ? sz.convert_min_size() : -1);
       ^
[572/941] Generate common tl source files
FAILED: ../tl/generate/auto/tl/ton_api.cpp ../tl/generate/auto/tl/ton_api.h ../tl/generate/auto/tl/ton_api.hpp ../tl/generate/auto/tl/ton_api_json.cpp ../tl/generate/auto/tl/ton_api_json.h ../tl/generate/auto/tl/lite_api.cpp ../tl/generate/auto/tl/lite_api.h ../tl/generate/auto/tl/lite_api.hpp ../tl/generate/auto/tl/tonlib_api.cpp ../tl/generate/auto/tl/tonlib_api.h ../tl/generate/auto/tl/tonlib_api.hpp ../tl/generate/auto/tl/tonlib_api_json.cpp ../tl/generate/auto/tl/tonlib_api_json.h 
cd /root/main.ton.dev/ton/tl/generate && /root/main.ton.dev/ton/build/tl/generate/generate_common
Illegal instruction
[577/941] Linking CXX sta...arty/rocksdb/librocksdb.a
ninja: build stopped: subcommand failed.

[575/941] Generate common tl source files
FAILED: ../tl/generate/auto/tl/ton_api.cpp ../tl/generate/auto/tl/ton_api.h ../tl/generate/auto/tl/ton_api.hpp ../tl/generate/auto/tl/ton_api_json.cpp ../tl/generate/auto/tl/ton_api_json.h ../tl/generate/auto/tl/lite_api.cpp ../tl/generate/auto/tl/lite_api.h ../tl/generate/auto/tl/lite_api.hpp ../tl/generate/auto/tl/tonlib_api.cpp ../tl/generate/auto/tl/tonlib_api.h ../tl/generate/auto/tl/tonlib_api.hpp ../tl/generate/auto/tl/tonlib_api_json.cpp ../tl/generate/auto/tl/tonlib_api_json.h 
cd /root/main.ton.dev/ton/tl/generate && /root/main.ton.dev/ton/build/tl/generate/generate_common
Illegal instruction
[581/941] Linking CXX sta...arty/rocksdb/librocksdb.a
ninja: build stopped: subcommand failed.

**Comment by finderom** [comment]
**+1 Same error**

[502/941] Generate common tl source files
FAILED: ../tl/generate/auto/tl/ton_api.cpp ../tl/generate/auto/tl/ton_api.h ../tl/generate/auto/tl/ton_api.hpp ../tl/generate/auto/tl/ton_                                     api_json.cpp ../tl/generate/auto/tl/ton_api_json.h ../tl/generate/auto/tl/lite_api.cpp ../tl/generate/auto/tl/lite_api.h ../tl/generate/au                                     to/tl/lite_api.hpp ../tl/generate/auto/tl/tonlib_api.cpp ../tl/generate/auto/tl/tonlib_api.h ../tl/generate/auto/tl/tonlib_api.hpp ../tl/g                                     enerate/auto/tl/tonlib_api_json.cpp ../tl/generate/auto/tl/tonlib_api_json.h
cd /root/main.ton.dev/ton/tl/generate && /root/main.ton.dev/ton/build/tl/generate/generate_common
Illegal instruction (core dumped)
[507/941] Building CXX object crypto/CMakeFiles/func.dir/func/parse-func.cpp.o
ninja: build stopped: subcommand failed.

**Comment by triklozoid** [comment]
You can try solution from #1 
Removing option `-DTON_ARCH=corei7-avx` from build.sh

**Comment by finderom** [comment]
> You can try solution from #1
> Removing option `-DTON_ARCH=corei7-avx` from build.sh

thanks, it works

**Comment by 50c3** [comment]
@papanomad535 Did you try the solution from #1 ?

**Comment by stakrspace** [comment]
> @papanomad535 Did you try the solution from #1 ?

yes, it helps
