### ISSUE TITLE
Build error[E0282]: type annotations needed

### ISSUE THREAD

**Issue by triklozoid** [tonlabs/main.ton.dev#4]
`./build.sh` fails with message: 
```
   Compiling ton_sdk v0.1.0 (https://github.com/tonlabs/TON-SDK.git?branch=0.21.200-rc#a60a2dcf)
error[E0282]: type annotations needed
   --> /home/triklozoid/.cargo/git/checkouts/ton-sdk-11823a0ea1fdf592/a60a2dc/ton_sdk/src/contract.rs:561:19
    |
561 |             &mut |ref mut key, ref mut value| -> Result<bool> {
    |                   ^^^^^^^^^^^ consider giving this closure parameter a type
    |
    = note: type must be known at this point

error: aborting due to previous error

For more information about this error, try `rustc --explain E0282`.
error: could not compile `ton_sdk`.
warning: build failed, waiting for other jobs to finish...
error: build failed

```

System info: 
```
Linux  4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```

**Comment by finderom** [comment]
**+1 i have same error**

```
  Compiling ton_sdk v0.1.0 (https://github.com/tonlabs/TON-SDK.git?branch=0.21.200-rc#a60a2dcf)
error[E0282]: type annotations needed
   --> /home/finderom/.cargo/git/checkouts/ton-sdk-11823a0ea1fdf592/a60a2dc/ton_sdk/src/contract.rs:561:19
    |
561 |             &mut |ref mut key, ref mut value| -> Result<bool> {
    |                   ^^^^^^^^^^^ consider giving this closure parameter a type
    |
    = note: type must be known at this point

error: aborting due to previous error

For more information about this error, try `rustc --explain E0282`.
error: could not compile `ton_sdk`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by mark99i** [comment]
in file
... git/checkouts/ton-sdk-11823a0ea1fdf592/a60a2dc/ton_sdk/src/contract.rs:561
try replacing it
`|ref mut key, ref mut value|`
to
`|mut key: SliceData, ref mut value|`

to keep the changes comment the lines in build.sh
```
#rm -rf "${TONOS_CLI_SRC_DIR}"
#git clone https://github.com/tonlabs/tonos-cli.git "${TONOS_CLI_SRC_DIR}"
```
and run ./build.sh

**Comment by stakrspace** [comment]
Got the same error:

Compiling ton_sdk v0.1.0 (https://github.com/tonlabs/TON-SDK.git?branch=0.21.200-rc#a60a2dcf)
error[E0282]: type annotations needed
   --> /root/.cargo/git/checkouts/ton-sdk-11823a0ea1fdf592/a60a2dc/ton_sdk/src/contract.rs:561:19
    |
561 |             &mut |ref mut key, ref mut value| -> Result<bool> {
    |                   ^^^^^^^^^^^ consider giving this closure parameter a type
    |
    = note: type must be known at this point

error: aborting due to previous error

For more information about this error, try `rustc --explain E0282`.
error: could not compile `ton_sdk`.
warning: build failed, waiting for other jobs to finish...
error: build failed




System info:

Linux 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

**Comment by BlackDiverX** [comment]
I got same error when build. I use fresh install of Ubuntu 18.04

**Comment by finderom** [comment]
> in file
> ... git/checkouts/ton-sdk-11823a0ea1fdf592/a60a2dc/ton_sdk/src/contract.rs:561
> try replacing it
> `|ref mut key, ref mut value|`
> to
> `|mut key: SliceData, ref mut value|`

It work, but please explain it.

**Comment by BlackDiverX** [comment]
> in file
> ... git/checkouts/ton-sdk-11823a0ea1fdf592/a60a2dc/ton_sdk/src/contract.rs:561
> try replacing it
> `|ref mut key, ref mut value|`
> to
> `|mut key: SliceData, ref mut value|`
> 
> to keep the changes comment the lines in build.sh
> 
> ```
> #rm -rf "${TONOS_CLI_SRC_DIR}"
> #git clone https://github.com/tonlabs/tonos-cli.git "${TONOS_CLI_SRC_DIR}"
> ```
> 
> and run ./build.sh

I am try use you solution after
`apt update && apt full-upgrade`
It Work. Thank you!

**Comment by mark99i** [comment]
> > in file
> > ... git/checkouts/ton-sdk-11823a0ea1fdf592/a60a2dc/ton_sdk/src/contract.rs:561
> > try replacing it
> > `|ref mut key, ref mut value|`
> > to
> > `|mut key: SliceData, ref mut value|`
> 
> It work, but please explain it.

the compiler needs the _key_ variable type
to find the type, I searched for where else the _get_next_u32()_ function is used.
I found using this function with the _SliceData_ type in the file
_.. git/checkouts/ton-labs-block-812d587b7e79a3a4/ba8ffcd/src/accounts.rs:258_
I assumed that the same type is used in the function _from_cells()_ in file _contract.rs:553_

but it's better to wait for the developers comments

**Comment by issakomi** [comment]
S. PR https://github.com/tonlabs/TON-SDK/pull/109/  (approved)

```
-  &mut |ref mut key, ref mut value| -> Result<bool> {
+  &mut |ref mut key: SliceData, ref mut value| -> Result<bool> {
```
