### ISSUE TITLE
error building ton-labs-assembler on Ubuntu 18.04

### ISSUE THREAD

**Issue by stakrspace** [tonlabs/main.ton.dev#40]
Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-147-generic x86_64)
rustc 1.53.0 (53cb7b09b 2021-06-17)

Updating git repository `https://github.com/tonlabs/ton-labs-assembler.git`
error: failed to download `zeroize v1.4.1`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/home/ton/.cargo/registry/src/github.com-1ecc6299db9ec823/zeroize-1.4.1/Cargo.toml`

Caused by:
  cargo-features = ["resolver"] was found in the wrong location, it should be set at the top of Cargo.toml before any tables

**Comment by joydark** [comment]
Please try `cargo update`

**Comment by stakrspace** [comment]
> Please try `cargo update`

solved, thanks
