### ISSUE TITLE
Deploy Multisignature wallet error

### ISSUE THREAD

**Issue by BlackDiverX** [tonlabs/main.ton.dev#7]
I got error when deploy Multisignature wallet
command:
`"${UTILS_DIR}/tonos-cli" deploy "${CONFIGS_DIR}/SafeMultisigWallet.tvc" '{"owners":["0xPUBLIC_KEY_FROM_msig.keys.json","0xPUBLIC_KEY_FROM_tonos-cli_genphrase"                               ],"reqConfirms":1}' --abi "${CONFIGS_DIR}/SafeMultisigWallet.abi.json" --sign /root/ton-keys/msig.keys.json`

Output command:
`Input arguments:
     tvc: /root/main.ton.dev/configs/SafeMultisigWallet.tvc
  params: {"owners":["0x212****","0x4df***"],"reqConfirms":1}
     abi: /root/main.ton.dev/configs/SafeMultisigWallet.abi.json
    keys: /root/ton-keys/msig.keys.json
      wc: None
Deploying...
Error: deploy failed: Inner SDK error.
 source: client
 code: 1006
 message: Message expired
 data.phase: null
 data.transaction_id: null
Error: 1
`

file /root/ton-keys/msig.keys.json:
`{
  "public": "2*******",
  "secret": "4*******"
}`

hostname: validator

file /root/ton-keys/validator.addr
`-1:d9*******`

validator status:

`./check_node_sync_status.sh
connecting to [127.0.0.1:3030]
local key: 59*******
remote key: DEA****
conn ready
unixtime                        1589039725
masterchainblock                        (-1,8000000000000000,32318):A7977102491363DFA5BF3DF3645F1C87A44BA1F2FAC09E98B1793C4137607524:67776A8792ED8D273AB5A511327F25A326A56C9B3540CC86A2A784EEFD1BAE57
masterchainblocktime                    1589039721
gcmasterchainblock                      (-1,8000000000000000,27602):FA2447CFE5083606F8F334CA616AEA2E176C0380CEF9425DF1211B48517B0811:4D9D5F140B6672F801F1AC8B25AC0015A64750CDA1A1143213658DBF936F6FFF
keymasterchainblock                     (-1,8000000000000000,28430):091A2E4D4D7DD7A736AC7335428EC4D41C0FC5FDF895CA016D97815EC5654ECC:D0846B3E4E618E5CAA54862E57FA3FB2FEAB16F6C1F11FD17916F8152CB2B3DB
knownkeymasterchainblock                        (-1,8000000000000000,28430):091A2E4D4D7DD7A736AC7335428EC4D41C0FC5FDF895CA016D97815EC5654ECC:D0846B3E4E618E5CAA54862E57FA3FB2FEAB16F6C1F11FD17916F8152CB2B3DB
rotatemasterchainblock                  (-1,8000000000000000,32255):AD5C290D101DCA92BF7FF547C60D149286A6F4858DAC439A709738AABB933BF8:0AADA9354AAFF7110B7376DD593A45BAD4D84DE3E54EF45084AFE4ECFCC83548
stateserializermasterchainseqno                 32315
shardclientmasterchainseqno                     27602
INFO: TIME_DIFF = -4`

**Comment by crtlib** [comment]
@BlackDiverX Did you send some tokens to the multi-sig wallet address? According to this doc, this will create the wallet in `Uninit` state: https://docs.ton.dev/86757ecb2/v/0/p/94921e-working-with-multisignature-wallet-in-tonos-cli. After that, the deploy should work.

**Comment by frstrtr** [comment]
--wc -1 resolves the issue

all validator addresses needs to use this parameter

and you need to get some funds on your wallet before 

You can ask for it here: 
https://forms.gle/zCH7dDiR2yC84m5m9

3.2.4. Deploy the multisignature code and data to the blockchain

**Comment by ar-tmp** [comment]
Is the issue still actual?

**Comment by frstrtr** [comment]
if manual were fixed - then no...

**Comment by ar-tmp** [comment]
Could you please check the latest validator deployment procedure https://docs.ton.dev/86757ecb2/p/60448f-run-automated-validator-single-custodian - it should be fixed there.

**Comment by Kenny-zhao** [comment]
In the current mainstream wallet products in the market, whoever has a mnemonic or private key can directly transfer funds away, which actually poses a great security risk.

    If there is an internal ghost in the exchange, the other party can easily transfer all the funds away; or multiple partners (bosses) manage the same wallet assets. Single signing may lead to asset control biased to one person, resulting in asset security problems.

    Uduncloud Wallet 3.0's multi-signature mode separates permissions. Partners participating in asset management through the multi-signature mode can customize the weight ratio of each partner in multi-signature management. When any partner participating in multi-signature sends When transferring transactions, some or all partners need to agree to complete the transfer, ensuring the safety of funds and balancing the authority of each manager.

**Comment by ASLanin** [comment]
Closed due to inactivity.
