### ISSUE TITLE
rust error[E0658]  during build the node

### ISSUE THREAD

**Issue by energius** [tonlabs/main.ton.dev#9]
Hello, trying to build the node using ./build.sh script
at the end the building got an error:
"
error[E0658] : use of unstable library feature 'alloc' " this library is unlikely to be stabilized in its current form or name (see issue #27783)
--> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/debug-helper-0.3.8/src/lib.rs:305:1
       |
305 |   extern crate alloc:
       |
error: aborting due previous error
For more information about this error, try 'rustc --explain E0658'

**Comment by energius** [comment]
solved, 
removed current rust and installed rust nightly version
$ apt-get --purge remove rustc
$ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
during installation choose:
nightly  
and if changed PATH then need to use command to add rustc to PATH
$ source $HOME/.cargo/env 

check rustc version 
$ rustc --version 
>>> rustc 1.45.0-nightly (9912925c2 202-05-10)

**Comment by ar-tmp** [comment]
Which OS and Rust version have you used when the problem occurred?

**Comment by ASLanin** [comment]
Due to a long response time we assume that it was an old rust version used initially. 
We're going to close the ticked since it does work with the latest stable rust version installed in OS.
